analytics: {}
color:
  brandColors:
    - '#2c2e3d'
    - '#e9e9e9'
    - '#444e5a'
    - '#729685'
    - '#9bafa7'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.62711
name: RBG001
opengraph: {}
purpose: []
typography_spectrum: 0.774122
