layout_spectrum: 0.4280344
color:
  saturation: 0.6020408
  brandStrength: 0.9382384
  lightness: 0.9403866
  brandColors:
    - '#394253'
    - '#F2C6BC'
    - '#AC919A'
    - '#B4CFC6'
    - '#916E77'
  rhythmicContrast: 0.8899033
typography_spectrum: 0.2142857
name: RBG001
